### ISSUE TITLE
Create a specific track for i386 support

### ISSUE THREAD

**Issue by brlin-tw** [Lin-Buo-Ren/bfg-snap#9]
It is possible to create a separate track to build the application against older bases, we need to maintain two git branches, though...

## Subtasks

* [ ] Create the `i386` Git branch based on pre-core22-migration
* [ ] Cherry-pick applicable changes after the migration on the main branch
* [ ] Apply for the creation of the `i386` track in the Snapcraft Forum
* [ ] Create a project on Launchpad
* [ ] Setup snap build from the `i386` git branch to the `i386` track on Launchpad.
* [ ] Migrate users from the `latest` track to the `i386` track

**Comment by brlin-tw** [comment]
Blocked by #11.
